/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv.index'
import { Route as TvIdRouteImport } from './routes/tv.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/tv': typeof TvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/movies'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/tv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/movies'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/tv'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/movies'
    | '/profile'
    | '/search'
    | '/watchlist'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/tv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  MovieIdRoute: typeof MovieIdRoute
  PersonIdRoute: typeof PersonIdRoute
  TvIdRoute: typeof TvIdRoute
  TvIndexRoute: typeof TvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  MovieIdRoute: MovieIdRoute,
  PersonIdRoute: PersonIdRoute,
  TvIdRoute: TvIdRoute,
  TvIndexRoute: TvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
